apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunk-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chunk
  template:
    metadata:
      labels:
        app: chunk
    spec:
      containers:
      - name: chunk
        image: nithindstud/chunk:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
